apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  POSTGRES_USER: "adminfiap"
  POSTGRES_PASSWORD: "m@_ssq@HJ7<h(+"
  POSTGRES_DB: "techchallenge"
  MP_USER_ID: "2333300249"
  MP_POS_ID: "111092408"
  MP_EXTERNAL_STORE_ID: "FIAP001"
  MP_EXTERNAL_POS_ID: "FIAP001CAIXA001"
  MP_AUTH_HEADER: "Bearer APP_USR-3275293218198108-031718-5526fd48d54fa3cf79471546ff5bec1f-2333300249"
  ENTRA_ID_TENANT_ID: "11c023fa-ce6c-495b-a8a3-8bef957a1695"
  ENTRA_ID_CLIENT_ID: "ba151a9f-6750-42c2-b4a1-0943c8401b3d"
  ENTRA_ID_CLIENT_SECRET: "iUL8Q~EkxcvQXK2i~.YQJQFqtRIjc5kkbbDm7bhZ"
  ENTRA_ID_TENANT_NAME: "entregatechchallenge03.onmicrosoft.com"